"""Shared constants. Crypto and bundle I/O live in later milestones."""

from __future__ import annotations

PROJECT_SCHEMA_VERSION = 1
BUNDLE_FORMAT_VERSION = 1

APP_NAME = "Audio Bundle"
APP_VERSION = "0.1.0"

BUNDLE_EXTENSION = ".audiobundle"
BUNDLE_MAGIC = b"AUDIOBUNDLE\x00\x00\x00\x00\x00"  # 16 bytes
BUNDLE_FOOTER_MAGIC = b"ABDLEND\x00"

MAX_NAME_LENGTH = 200
MAX_FILENAME_LENGTH = 255
MAX_BLOCKS_PER_PROJECT = 500
MAX_FOLDERS_PER_PROJECT = 500
MAX_FOLDER_DEPTH = 3
MAX_ITEMS_PER_BLOCK = 2000

AUDIO_EXTENSIONS: frozenset[str] = frozenset({".mp3", ".wav", ".m4a", ".aac"})
PDF_EXTENSIONS: frozenset[str] = frozenset({".pdf"})
SUPPORTED_EXTENSIONS: frozenset[str] = AUDIO_EXTENSIONS | PDF_EXTENSIONS

AES_KEY_SIZE = 32
GCM_NONCE_SIZE = 12
GCM_TAG_SIZE = 16
KDF_SALT_SIZE = 16
KDF_HASH_LEN = 32
KDF_ALGORITHM = "argon2id"
KDF_BUNDLE_WRAP = "bundle-key"

# Production Argon2id. Run off the UI thread; do not use these values in unit tests.
KDF_TIME_COST = 3
KDF_MEMORY_KIB = 64 * 1024
KDF_PARALLELISM = 1

# Tests only. Explicitly opted into via KdfProfile.TEST.
TEST_KDF_TIME_COST = 1
TEST_KDF_MEMORY_KIB = 32
TEST_KDF_PARALLELISM = 1

MAX_PASSWORD_BYTES = 1024
AAD_CHUNK_MAIN_WRAP = b"WKEY"
AAD_CHUNK_BLOCK_WRAP = b"BWKY"
AAD_CHUNK_OUTER_MANIFEST = b"EMAN"
AAD_CHUNK_INNER_MANIFEST = b"BMAN"
AAD_CHUNK_BLOB = b"BLOB"
